# Generated by Django 4.1.9 on 2023-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
