# Generated by Django 4.1.9 on 2023-08-04 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_fileversion_content_hash_fileversion_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileversion",
            old_name="uploaded_by",
            new_name="owner",
        ),
    ]
