# Generated by Django 4.1.9 on 2023-08-04 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0005_rename_uploaded_by_fileversion_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileversion",
            options={"ordering": ("file_name", "version_number"), "verbose_name": "File Version"},
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("content_hash", "version_number")},
        ),
    ]
