# Generated by Django 4.1.9 on 2023-08-04 08:06

from django.db import migrations, models
import file_versions.models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0007_alter_fileversion_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="user_defined_path",
            field=models.CharField(
                blank=True, max_length=512, null=True, validators=[file_versions.models.validate_path]
            ),
        ),
    ]
