# Generated by Django 4.1.9 on 2023-08-04 08:18

from django.db import migrations, models
import file_versions.models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0008_fileversion_user_defined_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileversion",
            name="user_defined_path",
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="file_name",
            field=models.CharField(max_length=512, validators=[file_versions.models.validate_path]),
        ),
    ]
