# Generated by Django 4.1.9 on 2023-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0009_remove_fileversion_user_defined_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="content_hash",
            field=models.TextField(unique=True),
        ),
    ]
